CREATE USER [NT SERVICE\MSSQLServerOLAPService] FOR LOGIN [NT SERVICE\MSSQLServerOLAPService] WITH DEFAULT_SCHEMA=[dbo]
GO
GRANT CONNECT TO [NT SERVICE\MSSQLServerOLAPService];
GO
GRANT SELECT ON dbo.dim_employee TO [NT SERVICE\MSSQLServerOLAPService];
GO
GRANT SELECT ON dbo.work_plan TO [NT SERVICE\MSSQLServerOLAPService];
GO
GRANT SELECT ON dbo.dim_clients TO [NT SERVICE\MSSQLServerOLAPService];
GO
GRANT SELECT ON dbo.orders TO [NT SERVICE\MSSQLServerOLAPService];
GO
GRANT SELECT ON dbo.calendar TO [NT SERVICE\MSSQLServerOLAPService];
GO
GRANT SELECT ON dbo.dim_services TO [NT SERVICE\MSSQLServerOLAPService];
GO
GRANT SELECT ON dbo.certificate_completed TO [NT SERVICE\MSSQLServerOLAPService];
GO
GRANT SELECT ON dbo.orders_completed TO [NT SERVICE\MSSQLServerOLAPService];
GO
GRANT SELECT ON dbo.vOrders TO [NT SERVICE\MSSQLServerOLAPService];
